name = "streaming-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

[[routes]]
pattern = "streaming.blackroad.io/*"
zone_name = "blackroad.io"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-chat"
database_id = "ec4efdfb-a76e-46fb-a821-1278e17e7b90"

[ai]
binding = "AI"

[vars]
AUTH_API = "https://auth.blackroad.io"
